services:
  memory:
    build: ./memory
    ports:
      - "50051:50051"
    restart: unless-stopped
  agent:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - memory
    restart: unless-stopped
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
    depends_on:
      - agent
    restart: unless-stopped
