// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: memory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type UserContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContextRequest) Reset() {
	*x = UserContextRequest{}
	mi := &file_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContextRequest) ProtoMessage() {}

func (x *UserContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContextRequest.ProtoReflect.Descriptor instead.
func (*UserContextRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{4}
}

func (x *UserContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContextResponse) Reset() {
	*x = UserContextResponse{}
	mi := &file_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContextResponse) ProtoMessage() {}

func (x *UserContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContextResponse.ProtoReflect.Descriptor instead.
func (*UserContextResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{5}
}

func (x *UserContextResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type Moment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Emotion       string                 `protobuf:"bytes,4,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Glyph         string                 `protobuf:"bytes,5,opt,name=glyph,proto3" json:"glyph,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Embedding     string                 `protobuf:"bytes,8,opt,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moment) Reset() {
	*x = Moment{}
	mi := &file_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moment) ProtoMessage() {}

func (x *Moment) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moment.ProtoReflect.Descriptor instead.
func (*Moment) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{6}
}

func (x *Moment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Moment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Moment) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Moment) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *Moment) GetGlyph() string {
	if x != nil {
		return x.Glyph
	}
	return ""
}

func (x *Moment) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Moment) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Moment) GetEmbedding() string {
	if x != nil {
		return x.Embedding
	}
	return ""
}

type SetMomentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moment        *Moment                `protobuf:"bytes,1,opt,name=moment,proto3" json:"moment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMomentRequest) Reset() {
	*x = SetMomentRequest{}
	mi := &file_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMomentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMomentRequest) ProtoMessage() {}

func (x *SetMomentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMomentRequest.ProtoReflect.Descriptor instead.
func (*SetMomentRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{7}
}

func (x *SetMomentRequest) GetMoment() *Moment {
	if x != nil {
		return x.Moment
	}
	return nil
}

type GetMomentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Since         int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	Until         int64                  `protobuf:"varint,4,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMomentsRequest) Reset() {
	*x = GetMomentsRequest{}
	mi := &file_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMomentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentsRequest) ProtoMessage() {}

func (x *GetMomentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentsRequest.ProtoReflect.Descriptor instead.
func (*GetMomentsRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{8}
}

func (x *GetMomentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMomentsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetMomentsRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *GetMomentsRequest) GetUntil() int64 {
	if x != nil {
		return x.Until
	}
	return 0
}

type GetMomentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moments       []*Moment              `protobuf:"bytes,1,rep,name=moments,proto3" json:"moments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMomentsResponse) Reset() {
	*x = GetMomentsResponse{}
	mi := &file_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMomentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentsResponse) ProtoMessage() {}

func (x *GetMomentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentsResponse.ProtoReflect.Descriptor instead.
func (*GetMomentsResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{9}
}

func (x *GetMomentsResponse) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

type SemanticSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{10}
}

func (x *SemanticSearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SemanticSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SemanticSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Moment              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResponse) Reset() {
	*x = SemanticSearchResponse{}
	mi := &file_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResponse) ProtoMessage() {}

func (x *SemanticSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResponse.ProtoReflect.Descriptor instead.
func (*SemanticSearchResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{11}
}

func (x *SemanticSearchResponse) GetResults() []*Moment {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_memory_proto protoreflect.FileDescriptor

const file_memory_proto_rawDesc = "" +
	"\n" +
	"\fmemory.proto\x12\x06memory\"M\n" +
	"\n" +
	"SetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\n" +
	"GetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"-\n" +
	"\x12UserContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x13UserContextResponse\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\"\xcb\x01\n" +
	"\x06Moment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\aemotion\x18\x04 \x01(\tR\aemotion\x12\x14\n" +
	"\x05glyph\x18\x05 \x01(\tR\x05glyph\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tembedding\x18\b \x01(\tR\tembedding\":\n" +
	"\x10SetMomentRequest\x12&\n" +
	"\x06moment\x18\x01 \x01(\v2\x0e.memory.MomentR\x06moment\"l\n" +
	"\x11GetMomentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\x12\x14\n" +
	"\x05until\x18\x04 \x01(\x03R\x05until\">\n" +
	"\x12GetMomentsResponse\x12(\n" +
	"\amoments\x18\x01 \x03(\v2\x0e.memory.MomentR\amoments\"F\n" +
	"\x15SemanticSearchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"B\n" +
	"\x16SemanticSearchResponse\x12(\n" +
	"\aresults\x18\x01 \x03(\v2\x0e.memory.MomentR\aresults2\x90\x03\n" +
	"\x11UserMemoryService\x12.\n" +
	"\x03Set\x12\x12.memory.SetRequest\x1a\x13.memory.SetResponse\x12.\n" +
	"\x03Get\x12\x12.memory.GetRequest\x1a\x13.memory.GetResponse\x12I\n" +
	"\x0eGetUserContext\x12\x1a.memory.UserContextRequest\x1a\x1b.memory.UserContextResponse\x12:\n" +
	"\tSetMoment\x12\x18.memory.SetMomentRequest\x1a\x13.memory.SetResponse\x12C\n" +
	"\n" +
	"GetMoments\x12\x19.memory.GetMomentsRequest\x1a\x1a.memory.GetMomentsResponse\x12O\n" +
	"\x0eSemanticSearch\x12\x1d.memory.SemanticSearchRequest\x1a\x1e.memory.SemanticSearchResponseB%Z#github.com/MyndScript/AGI/memory/pbb\x06proto3"

var (
	file_memory_proto_rawDescOnce sync.Once
	file_memory_proto_rawDescData []byte
)

func file_memory_proto_rawDescGZIP() []byte {
	file_memory_proto_rawDescOnce.Do(func() {
		file_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)))
	})
	return file_memory_proto_rawDescData
}

var file_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_memory_proto_goTypes = []any{
	(*SetRequest)(nil),             // 0: memory.SetRequest
	(*SetResponse)(nil),            // 1: memory.SetResponse
	(*GetRequest)(nil),             // 2: memory.GetRequest
	(*GetResponse)(nil),            // 3: memory.GetResponse
	(*UserContextRequest)(nil),     // 4: memory.UserContextRequest
	(*UserContextResponse)(nil),    // 5: memory.UserContextResponse
	(*Moment)(nil),                 // 6: memory.Moment
	(*SetMomentRequest)(nil),       // 7: memory.SetMomentRequest
	(*GetMomentsRequest)(nil),      // 8: memory.GetMomentsRequest
	(*GetMomentsResponse)(nil),     // 9: memory.GetMomentsResponse
	(*SemanticSearchRequest)(nil),  // 10: memory.SemanticSearchRequest
	(*SemanticSearchResponse)(nil), // 11: memory.SemanticSearchResponse
}
var file_memory_proto_depIdxs = []int32{
	6,  // 0: memory.SetMomentRequest.moment:type_name -> memory.Moment
	6,  // 1: memory.GetMomentsResponse.moments:type_name -> memory.Moment
	6,  // 2: memory.SemanticSearchResponse.results:type_name -> memory.Moment
	0,  // 3: memory.UserMemoryService.Set:input_type -> memory.SetRequest
	2,  // 4: memory.UserMemoryService.Get:input_type -> memory.GetRequest
	4,  // 5: memory.UserMemoryService.GetUserContext:input_type -> memory.UserContextRequest
	7,  // 6: memory.UserMemoryService.SetMoment:input_type -> memory.SetMomentRequest
	8,  // 7: memory.UserMemoryService.GetMoments:input_type -> memory.GetMomentsRequest
	10, // 8: memory.UserMemoryService.SemanticSearch:input_type -> memory.SemanticSearchRequest
	1,  // 9: memory.UserMemoryService.Set:output_type -> memory.SetResponse
	3,  // 10: memory.UserMemoryService.Get:output_type -> memory.GetResponse
	5,  // 11: memory.UserMemoryService.GetUserContext:output_type -> memory.UserContextResponse
	1,  // 12: memory.UserMemoryService.SetMoment:output_type -> memory.SetResponse
	9,  // 13: memory.UserMemoryService.GetMoments:output_type -> memory.GetMomentsResponse
	11, // 14: memory.UserMemoryService.SemanticSearch:output_type -> memory.SemanticSearchResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_memory_proto_init() }
func file_memory_proto_init() {
	if File_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_proto_goTypes,
		DependencyIndexes: file_memory_proto_depIdxs,
		MessageInfos:      file_memory_proto_msgTypes,
	}.Build()
	File_memory_proto = out.File
	file_memory_proto_goTypes = nil
	file_memory_proto_depIdxs = nil
}
