# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\x06memory\"9\n\nSetRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"*\n\nGetRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"%\n\x12UserContextRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"&\n\x13UserContextResponse\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t2\xbe\x01\n\x11UserMemoryService\x12.\n\x03Set\x12\x12.memory.SetRequest\x1a\x13.memory.SetResponse\x12.\n\x03Get\x12\x12.memory.GetRequest\x1a\x13.memory.GetResponse\x12I\n\x0eGetUserContext\x12\x1a.memory.UserContextRequest\x1a\x1b.memory.UserContextResponseB%Z#github.com/MyndScript/AGI/memory/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/MyndScript/AGI/memory/pb'
  _globals['_SETREQUEST']._serialized_start=24
  _globals['_SETREQUEST']._serialized_end=81
  _globals['_SETRESPONSE']._serialized_start=83
  _globals['_SETRESPONSE']._serialized_end=113
  _globals['_GETREQUEST']._serialized_start=115
  _globals['_GETREQUEST']._serialized_end=157
  _globals['_GETRESPONSE']._serialized_start=159
  _globals['_GETRESPONSE']._serialized_end=202
  _globals['_USERCONTEXTREQUEST']._serialized_start=204
  _globals['_USERCONTEXTREQUEST']._serialized_end=241
  _globals['_USERCONTEXTRESPONSE']._serialized_start=243
  _globals['_USERCONTEXTRESPONSE']._serialized_end=281
  _globals['_USERMEMORYSERVICE']._serialized_start=284
  _globals['_USERMEMORYSERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
