# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc  # type: ignore

from . import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserMemoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
    self.Set = channel.unary_unary(  # type: ignore
        '/memory.UserMemoryService/Set',
        request_serializer=memory__pb2.SetRequest.SerializeToString,  # type: ignore[attr-defined]
        response_deserializer=memory__pb2.SetResponse.FromString,  # type: ignore[attr-defined]
        _registered_method=True)
    self.Get = channel.unary_unary(  # type: ignore
        '/memory.UserMemoryService/Get',
        request_serializer=memory__pb2.GetRequest.SerializeToString,  # type: ignore[attr-defined]
        response_deserializer=memory__pb2.GetResponse.FromString,  # type: ignore[attr-defined]
        _registered_method=True)
    self.GetUserContext = channel.unary_unary(  # type: ignore
        '/memory.UserMemoryService/GetUserContext',
        request_serializer=memory__pb2.UserContextRequest.SerializeToString,  # type: ignore[attr-defined]
        response_deserializer=memory__pb2.UserContextResponse.FromString,  # type: ignore[attr-defined]
        _registered_method=True)


class UserMemoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserMemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Set': grpc.unary_unary_rpc_method_handler(
            servicer.Set,
            request_deserializer=memory__pb2.SetRequest.FromString,  # type: ignore[attr-defined]
            response_serializer=memory__pb2.SetResponse.SerializeToString,  # type: ignore[attr-defined]
        ),
        'Get': grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=memory__pb2.GetRequest.FromString,  # type: ignore[attr-defined]
            response_serializer=memory__pb2.GetResponse.SerializeToString,  # type: ignore[attr-defined]
        ),
        'GetUserContext': grpc.unary_unary_rpc_method_handler(
            servicer.GetUserContext,
            request_deserializer=memory__pb2.UserContextRequest.FromString,  # type: ignore[attr-defined]
            response_serializer=memory__pb2.UserContextResponse.SerializeToString,  # type: ignore[attr-defined]
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.UserMemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.UserMemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserMemoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/memory.UserMemoryService/Set',
            memory__pb2.SetRequest.SerializeToString,  # type: ignore[attr-defined]
            memory__pb2.SetResponse.FromString,  # type: ignore[attr-defined]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)  # type: ignore

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/memory.UserMemoryService/Get',
            memory__pb2.GetRequest.SerializeToString,  # type: ignore[attr-defined]
            memory__pb2.GetResponse.FromString,  # type: ignore[attr-defined]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)  # type: ignore

    @staticmethod
    def GetUserContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            '/memory.UserMemoryService/GetUserContext',
            memory__pb2.UserContextRequest.SerializeToString,  # type: ignore[attr-defined]
            memory__pb2.UserContextResponse.FromString,  # type: ignore[attr-defined]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)  # type: ignore
